# Generated by Django 3.1.1 on 2020-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=25)),
                ('short_description', models.CharField(max_length=256)),
                ('wiki_link', models.URLField(help_text='Provide a link to know more...')),
                ('country_flag', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='country_info',
        ),
    ]
